title: hotaery
author: hotaery
subtitle: "A blog about my life and my thoughts"

url: "https://hotaery.github.io"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/rhl-bthr/parchment"
footer_text: "Theme by rhl-bthr"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Home"
   link: "/"
 - name: "Tags"
   link: "tags"
 - name: "About"
   link: "about"
